### ISSUE TITLE
activating revisions - what about non-fingerprinted files?

### ISSUE THREAD

**Issue by jpaas** [ember-cli-deploy/ember-cli-deploy-s3-index#19]
One of the head scratchers I've had since I started using the original s3-index adapter was the fact that other non-fingerprinted files like favicon.icon, robots.txt, crossdomain.xml aren't really handled. I can switch revisions, but these other files are not changed, and therefore are just the last version that happened to be uploaded by the s3 plugin. Does it bother anyone else that there is no way of switching revisions for these files, or am I just being pedantic?

**Comment by achambers** [comment]
Hi @jpaas. This is something in the back of my mind but to be honest it isn't something that has come up as a pain point for people. We haven't had anyone screaming that it is a problem for them so it just hasn't really crept up our priority list.

Is this something that is an actual problem for you?

**Comment by jpaas** [comment]
No it doesn't really keep me awake at night. I just felt it had to be said in case it was an issue for someone. Feel free to close.

**Comment by achambers** [comment]
Thinking about it, do those things actually only matter for activated revisions? Just thinking through things. These files probably don't matter for non activated revisions.

So could it be that maybe upon activating a revision, those files are updated? Just thinking through the logistics of it.

**Comment by jpaas** [comment]
I suppose that for each revision, those files would have to be stashed somewhere until the revision is activated. Upon activation the "non-fingerprinted" files from the current revision would be removed, and the ones for the new revision would get moved into their respective locations.

**Comment by achambers** [comment]
Yeh, I'm not sure about actual implementation but sounds like something like that is what is needed.....

I'm going to close this issue as it doesn't really belong in this plugin anyway. So, maybe raise an RFC on the ember-cli-deploy main repo if it becomes a thing of nightmares for you :)

**Comment by yankeeinlondon** [comment]
I think the non-fingerprinted files should be uploaded with an appropriate _Expires_ property set. Without that you must manually "invalidate" content at the Cloudfront level and this is not elegant or fast. Is this possible with this plugin? I haven't looked yet but noticed that the _deploy-s3_ addon has expires pegged at a maximum interval.

**Comment by yankeeinlondon** [comment]
I typically set my a `index.html` to 15 seconds, most of the others to 84600.

**Comment by LevelbossMike** [comment]
I didn't quite get that. What do you want this plugin to do exactly?

Do you want to be able to configure the cache headers for index.html and/or other non-fingerprinted files?

I think setting cache headers on a per-file basis for asset files could be done in the s3 plugin and index.html should be done in this plugin. Did I understand you correctly @ksnyde ?

**Comment by LevelbossMike** [comment]
If you have something that is cached and you want to invalidate after a deploy has finished you can do that via https://github.com/simplabs/ember-cli-deploy-webhooks by sending an invalidation request to your CDN's api in the `didActivate`-hook. That of course can take a long time for cloudfront but you can get 'instant' cache purging with different CDN providers like [fastly](https://www.fastly.com/) or [keyCDN](https://www.keycdn.com/)

**Comment by yankeeinlondon** [comment]
When you "put" files to S3 there are two caching parameters that can be set `expires` and `cache-control`. For fingerprinted files it almost always makes sense to set these to the maximum amount but for signature (aka, non fingerprinted) files it is a very useful set of parameter to have exposed.

Here's a bash script that I'm using on a few projects. It works perfectly well but I would like to get off of it and onto _ember-cli-deploy_:

```
aws s3 sync ./fonts s3://bucket.name/fonts --cache-control max-age=63072000 --expires "Sat, 01 Jan 2035 12:00:00 GMT"
aws s3 sync ./fonts/*.woff2 s3://bucket.name/fonts --cache-control max-age=63072000 --expires "Sat, 01 Jan 2035 12:00:00 GMT" --content-type application/font-woff 
aws s3 cp ./index.html s3://bucket.name --cache-control max-age=10 
aws s3 cp ./robots.txt s3://bucket.name --cache-control max-age=3600 
aws s3 cp ./crossdomain.xml s3://bucket.name --cache-control max-age=86400 
```

**Comment by yankeeinlondon** [comment]
I agree that this functionality should reside in `ember-cli-deploy-s3` but right now it's hard coded (I've raised an issue there). I was just hoping that I might get this functionality here and in fact since this addon's responsibility is `index.html` it seems maybe even more important. As you mentioned, the Cloudfront CDN does not work quickly with invalidations so I'm happy to compromise with the client having a low latency (aka, CDN) call to index.html.

**Comment by LevelbossMike** [comment]
Wouldn't it be enough to clear the CDN cache on deployment for these files? I assume you have a CDN in front of your assets before serving to your users.

I implemented the possibility to add cache-headers on a branch and additional meta data like surrogate-keys for fastly. This branch needs some cleanup before merging to master but what I tend to think is that actually what one wants to do is to serve index.html (with this plugin) via a CDN to users because of latency and clear this cache as soon as a deploy is complete right?! That's of course an issue with cloudfront as the invalidation takes so long but what I suggest in this case is simply to switch to a different CDN solution.

I know that's not an ideal solution as switching CDN might be annoying and it's definitely possible to add the cache-header option too but I think serving via a CDN and invalidating on didActivate is actually the way to go instead of relying on cache-headers.

What are your thoughts about that @ksnyde?

**Comment by yankeeinlondon** [comment]
I think the full AWS stack is always going to be a very popular option and I like _Cloudfront_ in many ways. To make it work for a "lightning" build all you need is the aforementioned setting in S3 (as Cloudfront will proxy it through to the client). It's true that this in one way is less graceful because it effectively "expires" the `index.html` entry point every 10 seconds but with SPA's this is typically just loaded once anyway so in "real life" it's pretty much a non-issue. This kind of solution, rather than forcing a CDN to invalidate the content, also fits Occum's razor reductionist principles.

**Comment by yankeeinlondon** [comment]
Also, one should consider the expiry contract not only between S3 and the CDN but also the client browser and the CDN (or S3 if connecting directly). If a browser is told that the timeout for the `index.html` is 3 months out and the user leaves and comes back (aka, doesn't do a hard reload) then the browser will just use what it has in it's own cache. This is clearly not what you want. It will result in users using local cache for the entry point to the SPA and the entry point then referencing stale fingerprinted files.

**Comment by LevelbossMike** [comment]
Yes of course the CDN shouldn't tell the client to cache the content because that misses the whole point of the lightning strategy.

I can add the possibility for setting cache-headers into the plugin but I am still not convinced that this isn't actually a problem of the CDN provider (slow cache invalidation) and just an somewhat ok workaround.

I think I'll find the time to add the ability to set cache-headers this week.

**Comment by yankeeinlondon** [comment]
@LevelbossMike  great, will be an avid user of the feature!
